# Generated by Django 5.2.5 on 2025-08-12 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_birthdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('payment_screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('confirmed', models.BooleanField(default=False)),
                ('download_link', models.URLField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
