# Generated by Django 5.2.5 on 2025-08-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userdocumentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocumentrequest',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
