# Generated by Django 5.2.5 on 2025-08-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userdocumentrequest_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocumentrequest',
            name='download_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
