# Generated by Django 5.2.5 on 2026-06-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userdocumentrequest_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocumentrequest',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
