# Generated by Django 5.2.5 on 2026-09-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_email_otp_customuser_email_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocumentrequest',
            name='form_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
